"""added genres column to venues table

Revision ID: 1345ec53cd93
Revises: 9150b37361cc
Create Date: 2022-08-13 07:53:17.076029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1345ec53cd93'
down_revision = '9150b37361cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('genres', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'genres')
    # ### end Alembic commands ###
